opt_in_rules:
  # - lower_acl_than_parent          
  # - implicit_return        
  # - for_where
  # - explicit_acl                                                    
  # - explicit_top_level_acl                 
  # - explicit_type_interface   
  # - trailing_closure
  # - convenience_type            
  # - force_cast
  # - vertical_whitespace_closing_braces     
  # - vertical_whitespace_opening_braces       
  # - multiline_arguments_brackets   
  # - legacy_objc_type  
  # - file_types_order    
  # - type_contents_order
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - class_delegate_protocol
  - large_tuple
  - force_try
  # - weak_delegate
  - closure_spacing
  - direct_return
  - leading_whitespace
  - yoda_condition
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - closure_body_length
  - void_return
  - closure_end_indentation
  - collection_alignment
  - fatal_error_message
  - redundant_self_in_closure              
  - redundant_set_access_control           
  - redundant_string_enum_value            
  - redundant_void_return      
  - mark
  - sorted_imports
  - unavailable_condition
  - unavailable_function
  - void_function_in_ternary
  - quick_discouraged_call                 
  - quick_discouraged_focused_test         
  - quick_discouraged_pending_test   
  - unhandled_throwing_task       
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - nimble_operator
  - nesting
  - local_doc_comment
  - let_var_whitespace
  - legacy_multiple                        
  - legacy_random    
  - computed_accessors_order
  - ns_number_init_as_function_reference
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - syntactic_sugar
  - switch_case_alignment
  - statement_position
  - private_over_fileprivate               
  - private_subject                        
  - private_unit_test     
  - prohibited_super_call 
  - empty_xctest_method
  - superfluous_disable_command            
  - explicit_init                           
  - single_test_class  
  - discouraged_direct_init                
  - discouraged_none_name                  
  - discouraged_object_literal   
  - unowned_variable_capture               
  - untyped_error_in_catch 
  - redundant_type_annotation  
  - implicit_getter     
  - modifier_order
  - notification_center_detachment                
  - nsobject_prefer_isequal  
  - sorted_first_last    
  - strong_iboutlet
  - shorthand_operator                     
  - shorthand_optional_binding                                 
  - strict_fileprivate    
  - literal_expression_end_indentation 
  - function_default_parameter_at_end                         
  - is_disjoint
  - duplicate_conditions
  - inclusive_language                     
  - invalid_swiftlint_command     
  - joined_default_parameter            
  - legacy_hashing    
  - no_extension_access_modifier    
  - prefer_nimble    
  - orphaned_doc_comment                      
  - no_fallthrough_only 
  - discarded_notification_center_observer
  - valid_ibinspectable
  - multiline_arguments      
  - protocol_property_accessors_order    
  - pattern_matching_keywords              
  - period_spacing   
  - optional_enum_case_matching
  - operator_whitespace
  - extension_access_modifier
  - prefer_self_type_over_type_of_self     
  - prefer_zero_over_explicit_init  
  - empty_parentheses_with_trailing_closure
  - duplicated_key_in_dictionary_literal
  - override_in_extension
  - generic_type_name
  - identical_operands
  - flatmap_over_map_reduce
  - dynamic_inline
  - redundant_discardable_let
  - superfluous_else   
  - contains_over_filter_count  
  - vertical_parameter_alignment           
  - vertical_parameter_alignment_on_call   

closure_body_length:
  - 70 # should be downgrade to 30
  - 100

large_tuple:
   - 3
   - 4

disabled_rules:
  - force_cast
  - cyclomatic_complexity                  
  - file_header                            
  - file_length                            
  - file_name       
  - function_body_length                   
  - function_parameter_count                                   
  - identifier_name                                                                                   
  - line_length                                                       
  - multiline_function_chains              
  - multiline_literal_brackets             
  - multiline_parameters                   
  - multiline_parameters_brackets          
  - multiple_closures_with_trailing_closure                   
  - no_magic_numbers                                                
  - opening_brace                          
  - prefixed_toplevel_constant               
  - redundant_nil_coalescing               
  - redundant_objc_attribute               
  - redundant_optional_initialization                  
  - required_deinit                        
  - return_value_from_void_function        
  - self_in_property_initialization                      
  - trailing_semicolon                     
  - type_body_length                       
  - type_name                              
  - unneeded_break_in_switch                                                                     
  - unneeded_synthesized_initializer
  - for_where
